apiVersion: v1
kind: ConfigMap
metadata:
  name: translateapp-config
  namespace: translateapp
data:
  # Frontend
  MINIO_ENDPOINT: "http://minio-service:9000"
  MINIO_PUBLIC_URL: "http://minio-service:9000"
  MINIO_BUCKET: "voice-profiles"
  MINIO_REGION: "us-east-1"
  NEXT_PUBLIC_WS_URL: "wss://YOUR_DOMAIN/ws"

  # Backend
  DEVICE_PREFERENCE: "auto"
  WHISPER_MODEL_SIZE: "medium"
